### ISSUE TITLE
Teacher ratings 

### ISSUE THREAD

**Issue by kajchang** [WhizardXD/arenarolodex#32]
I made a [website](https://studentsreview.me) with a database of Lowell announcers and teacher reviews, do you guys want to integrate ratings or links to review pages into the UI? Thanks for work on arenarolodex!

**Comment by areyoualex** [comment]
Hi! Though it does seem like a good idea in theory, arenarolodex is somewhat associated with the counseling department and sponsoring a list of teacher ratings would anger many teachers and counselors and we'd definitely get into trouble. Thank you for the suggestion, though.
